language: ruby
rvm:
 - "2.0.0"
 - "1.9.2"
 - "1.9.3"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec middleman build

# script: bundle exec rspec spec